export default function sitemap(){const base='https://atomicwalletuserguide.vercel.app';return [{url:base+'/',lastModified:new Date(),changeFrequency:'weekly',priority:1},
    {url:base+'/atomic-wallet/',lastModified:new Date(),changeFrequency:'monthly',priority:0.95},
    {url:base+'/atomic-wallet-login/',lastModified:new Date(),changeFrequency:'monthly',priority:0.95},
    {url:base+'/atomic-wallet-balance-not-showing/',lastModified:new Date(),changeFrequency:'monthly',priority:0.95},
    {url:base+'/atomic-wallet-not-working/',lastModified:new Date(),changeFrequency:'monthly',priority:0.95},
    {url:base+'/atomic-wallet-transaction-pending/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-connection-problem/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-sync/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-password/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-update/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-backup/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-restore/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-staking/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-swap/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-support/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-app/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-download/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-web3/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-extension/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
    {url:base+'/atomic-wallet-security/',lastModified:new Date(),changeFrequency:'monthly',priority:0.8},
];}